### ISSUE TITLE
Apostrophe causing invalid characters

### ISSUE THREAD

**Issue by rwarner** [micro-nova/AmpliPiWallPanel#31]
When changing a Zone from `Zone 1` to `Ryan's Office` it shows garbled text between the N and S. I noticed the keyboard on the device does not have an apostrophe so figured it would be worth mentioning. Just ended up getting rid of the apostrophe in the name for now so it looks fine.

**Comment by jonahshader** [comment]
The current fonts in the display firmware support all the characters from the iso-8859-1 encodings. The ' (U+0027) character seems to work but other similar ones like ʼ (U+02BC) aren't supported. Maybe one of these other characters was used in  `Ryan's Office`?

Apparently [micropython can only encode text as utf-8](https://forum.micropython.org/viewtopic.php?t=9100), so unsupported characters are being interpreted by the display as iso-8859-1 characters. Switching the fonts to use subsets of utf-8 will make the invalid characters blank (which isn't exactly a fix, but its better than garbled text). 

I'm currently working on this so a fix should be available soon.

**Comment by rwarner** [comment]
Thanks for the update @jonahshader -- fwiw, I changed the Zone name directly in the AmpliPi web gui

**Comment by jonahshader** [comment]
I included this fix in the latest pre-release, and will include it in the next public release.
