### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPiWallPanel#7]
- [x] Modify stream select page to have icons
- [x] Extend slider UI element to make it easier to slide
- [x] Finish implementing designs in nextion
- [x] Add update progress indicator screen

**Comment by rickballard** [comment]
A few optional colour schemes might be nice.  This device is usually prominent on a home's wall so it needs to be wife compatible.  And to this end,  the volume slider should ALWAYS show the zone(s) that it is currently set to control.
